/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ModalComponent {
    'imagesLink': string[];
    'indexImageShowed': number;
  }
  interface MyComponent {
    'images': string[];
  }
}

declare global {


  interface HTMLModalComponentElement extends Components.ModalComponent, HTMLStencilElement {}
  var HTMLModalComponentElement: {
    prototype: HTMLModalComponentElement;
    new (): HTMLModalComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'modal-component': HTMLModalComponentElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface ModalComponent extends JSXBase.HTMLAttributes<HTMLModalComponentElement> {
    'imagesLink'?: string[];
    'indexImageShowed'?: number;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    'images'?: string[];
  }

  interface IntrinsicElements {
    'modal-component': ModalComponent;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


